//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarahGeoDataUpload
{
    using System;
    using System.Collections.Generic;
    
    public partial class physfact_rev
    {
        public int Id { get; set; }
        public string wbcode { get; set; }
        public string country { get; set; }
        public string areakm2 { get; set; }
        public string cen_lat { get; set; }
        public string cen_lon { get; set; }
        public string elev { get; set; }
        public string distcr { get; set; }
        public string distc { get; set; }
        public string distr { get; set; }
        public string tropicar { get; set; }
        public string troppop { get; set; }
        public string lc100km { get; set; }
        public string lcr100km { get; set; }
        public string pop95 { get; set; }
        public string pdenpavg { get; set; }
        public string pop100km { get; set; }
        public string pop100cr { get; set; }
        public string cen_c { get; set; }
        public string cen_cr { get; set; }
    }
}
